services:
  redis:
    image: redis:latest
    container_name: celery_redis
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_app
    volumes:
      - ./app:/app/app 
    # working_dir: /app
    command: ["celery", "-A", "app.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    volumes:
      - ./app:/app/app
    working_dir: /app
    command: ["celery", "-A", "app.celery_app", "beat", "--loglevel=info"]
    depends_on:
      - redis
      - celery_app

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
    - "5555:5555"
    expose:
      - "5555"
    depends_on:
      - redis
      - celery_app
